src/Entity/Paper.php
<?php

namespace App\Entity;

use App\Repository\PaperRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PaperRepository::class)]
class Paper
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column]
    private ?float $width = null;

    #[ORM\Column]
    private ?float $height = null;

    #[ORM\Column]
    private ?int $weight = null;

    #[ORM\Column]
    private ?float $price_per_sheet = null;

    #[ORM\ManyToOne(inversedBy: 'papers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?PrintingMethod $printingMethod = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getWidth(): ?float
    {
        return $this->width;
    }

    public function setWidth(float $width): static
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight(): ?float
    {
        return $this->height;
    }

    public function setHeight(float $height): static
    {
        $this->height = $height;

        return $this;
    }

    public function getWeight(): ?int
    {
        return $this->weight;
    }

    public function setWeight(int $weight): static
    {
        $this->weight = $weight;

        return $this;
    }

    public function getPricePerSheet(): ?float
    {
        return $this->price_per_sheet;
    }

    public function setPricePerSheet(float $price_per_sheet): static
    {
        $this->price_per_sheet = $price_per_sheet;

        return $this;
    }

    public function getPrintingMethod(): ?PrintingMethod
    {
        return $this->printingMethod;
    }

    public function setPrintingMethod(?PrintingMethod $printingMethod): static
    {
        $this->printingMethod = $printingMethod;

        return $this;
    }
}

src/Form/PaperType.php
<?php

namespace App\Form;

use App\Entity\Paper;
use App\Entity\PrintingMethod;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;



class PaperType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('width')
            ->add('height')
            ->add('weight')
            ->add('price_per_sheet')
            ->add('printingMethod', EntityType::class, [
                'class' => PrintingMethod::class,
                'choice_label' => 'name', // the field shown in the dropdown
                'placeholder' => 'Select a printing method',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Paper::class,
        ]);
    }
}

src/Controller/PaperController.php
<?php

namespace App\Controller;

use App\Entity\Paper;
use App\Form\PaperType;
use App\Repository\PaperRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/paper')]
final class PaperController extends AbstractController
{
    #[Route(name: 'app_paper_index', methods: ['GET'])]
    public function index(PaperRepository $paperRepository): Response
    {
        return $this->render('paper/index.html.twig', [
            'papers' => $paperRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_paper_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $paper = new Paper();
        $form = $this->createForm(PaperType::class, $paper);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($paper);
            $entityManager->flush();

            return $this->redirectToRoute('app_paper_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('paper/new.html.twig', [
            'paper' => $paper,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_paper_show', methods: ['GET'])]
    public function show(Paper $paper): Response
    {
        return $this->render('paper/show.html.twig', [
            'paper' => $paper,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_paper_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Paper $paper, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PaperType::class, $paper);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_paper_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('paper/edit.html.twig', [
            'paper' => $paper,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_paper_delete', methods: ['POST'])]
    public function delete(Request $request, Paper $paper, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$paper->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($paper);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_paper_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/paper/_delete_form.html.twig
<form method="post" action="{{ path('app_paper_delete', {'id': paper.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ paper.id) }}">
    <button class="btn">Delete</button>
</form>

templates/paper/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/paper/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Paper{% endblock %}

{% block body %}
    <h1>Edit Paper</h1>

    {{ include('paper/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_paper_index') }}">back to list</a>

    {{ include('paper/_delete_form.html.twig') }}
{% endblock %}

templates/paper/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paper index{% endblock %}

{% block body %}
    <h1>Paper index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Width</th>
                <th>Height</th>
                <th>Weight</th>
                <th>Price_per_sheet</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for paper in papers %}
            <tr>
                <td>{{ paper.id }}</td>
                <td>{{ paper.name }}</td>
                <td>{{ paper.width }}</td>
                <td>{{ paper.height }}</td>
                <td>{{ paper.weight }}</td>
                <td>{{ paper.pricePerSheet }}</td>
                <td>
                    <a href="{{ path('app_paper_show', {'id': paper.id}) }}">show</a>
                    <a href="{{ path('app_paper_edit', {'id': paper.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_paper_new') }}">Create new</a>
{% endblock %}

templates/paper/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Paper{% endblock %}

{% block body %}
    <h1>Create new Paper</h1>

    {{ include('paper/_form.html.twig') }}

    <a href="{{ path('app_paper_index') }}">back to list</a>
{% endblock %}

templates/paper/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paper{% endblock %}

{% block body %}
    <h1>Paper</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ paper.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ paper.name }}</td>
            </tr>
            <tr>
                <th>Width</th>
                <td>{{ paper.width }}</td>
            </tr>
            <tr>
                <th>Height</th>
                <td>{{ paper.height }}</td>
            </tr>
            <tr>
                <th>Weight</th>
                <td>{{ paper.weight }}</td>
            </tr>
            <tr>
                <th>Price_per_sheet</th>
                <td>{{ paper.pricePerSheet }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_paper_index') }}">back to list</a>

    <a href="{{ path('app_paper_edit', {'id': paper.id}) }}">edit</a>

    {{ include('paper/_delete_form.html.twig') }}
{% endblock %}