src/Entity/HotFoil.php
<?php

namespace App\Entity;

use App\Repository\HotFoilRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HotFoilRepository::class)]
class HotFoil
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $setup_cost = null;

    #[ORM\Column]
    private ?float $per_quantity_multiplier = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSetupCost(): ?float
    {
        return $this->setup_cost;
    }

    public function setSetupCost(float $setup_cost): static
    {
        $this->setup_cost = $setup_cost;

        return $this;
    }

    public function getPerQuantityMultiplier(): ?float
    {
        return $this->per_quantity_multiplier;
    }

    public function setPerQuantityMultiplier(float $per_quantity_multiplier): static
    {
        $this->per_quantity_multiplier = $per_quantity_multiplier;

        return $this;
    }
}

src/Form/HotFoilType.php
<?php

namespace App\Form;

use App\Entity\HotFoil;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class HotFoilType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('setup_cost')
            ->add('per_quantity_multiplier')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => HotFoil::class,
        ]);
    }
}

src/Controller/HotFoilController.php
<?php

namespace App\Controller;

use App\Entity\HotFoil;
use App\Form\HotFoilType;
use App\Repository\HotFoilRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/hot/foil')]
final class HotFoilController extends AbstractController
{
    #[Route(name: 'app_hot_foil_index', methods: ['GET'])]
    public function index(HotFoilRepository $hotFoilRepository): Response
    {
        return $this->render('hot_foil/index.html.twig', [
            'hot_foils' => $hotFoilRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_hot_foil_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $hotFoil = new HotFoil();
        $form = $this->createForm(HotFoilType::class, $hotFoil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($hotFoil);
            $entityManager->flush();

            return $this->redirectToRoute('app_hot_foil_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('hot_foil/new.html.twig', [
            'hot_foil' => $hotFoil,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_hot_foil_show', methods: ['GET'])]
    public function show(HotFoil $hotFoil): Response
    {
        return $this->render('hot_foil/show.html.twig', [
            'hot_foil' => $hotFoil,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_hot_foil_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, HotFoil $hotFoil, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(HotFoilType::class, $hotFoil);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_hot_foil_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('hot_foil/edit.html.twig', [
            'hot_foil' => $hotFoil,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_hot_foil_delete', methods: ['POST'])]
    public function delete(Request $request, HotFoil $hotFoil, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$hotFoil->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($hotFoil);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_hot_foil_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/hot_foil/_delete_form.html.twig
<form method="post" action="{{ path('app_hot_foil_delete', {'id': hot_foil.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ hot_foil.id) }}">
    <button class="btn">Delete</button>
</form>

templates/hot_foil/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/hot_foil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit HotFoil{% endblock %}

{% block body %}
    <h1>Edit HotFoil</h1>

    {{ include('hot_foil/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_hot_foil_index') }}">back to list</a>

    {{ include('hot_foil/_delete_form.html.twig') }}
{% endblock %}

templates/hot_foil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HotFoil index{% endblock %}

{% block body %}
    <h1>HotFoil index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Setup_cost</th>
                <th>Per_quantity_multiplier</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for hot_foil in hot_foils %}
            <tr>
                <td>{{ hot_foil.id }}</td>
                <td>{{ hot_foil.setupCost }}</td>
                <td>{{ hot_foil.perQuantityMultiplier }}</td>
                <td>
                    <a href="{{ path('app_hot_foil_show', {'id': hot_foil.id}) }}">show</a>
                    <a href="{{ path('app_hot_foil_edit', {'id': hot_foil.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_hot_foil_new') }}">Create new</a>
{% endblock %}

templates/hot_foil/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New HotFoil{% endblock %}

{% block body %}
    <h1>Create new HotFoil</h1>

    {{ include('hot_foil/_form.html.twig') }}

    <a href="{{ path('app_hot_foil_index') }}">back to list</a>
{% endblock %}

templates/hot_foil/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}HotFoil{% endblock %}

{% block body %}
    <h1>HotFoil</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ hot_foil.id }}</td>
            </tr>
            <tr>
                <th>Setup_cost</th>
                <td>{{ hot_foil.setupCost }}</td>
            </tr>
            <tr>
                <th>Per_quantity_multiplier</th>
                <td>{{ hot_foil.perQuantityMultiplier }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_hot_foil_index') }}">back to list</a>

    <a href="{{ path('app_hot_foil_edit', {'id': hot_foil.id}) }}">edit</a>

    {{ include('hot_foil/_delete_form.html.twig') }}
{% endblock %}